### PR TITLE
Add multi domain support with vhost library.

### PR DESCRIPTION
**Pull request by namikazebadri**
Hi Ken,

I have been using express-auto-routes for some of my projects. It helps me a lot in my works, thanks for developing a really useful stuff. 

Recently, i am developing a kind of project setup for API development where the main purpose is to ease development of API for developer. Some of the features are providing **simulation of responses for quick frontend prototyping** and **multi domain support**. I am using your express-auto-routes for providing path auto routes.

Your auto routes is working with express vhost actually. But there are some changes where i must do to get it get along nicely with vhost library.

I created this pull request for you to review. I have created examples of vhost auto routes setup on /example/vhost.js. I hope my changes can contribute some improvement to your nice library.

Best Regards

### CODE REVIEW

**Comment by kenberkeley** [comment]
I marked this repo as `DEPRECATED`, so maybe you should create your own npm package such as `@namikazebadri/express-auto-routes`

**Comment by namikazebadri** [comment]
> I marked this repo as `DEPRECATED`, so maybe you should create your own npm package such as `@namikazebadri/express-auto-routes`

owh.., okay ken.., thank you very much..,

**Comment by kenberkeley** [comment]
I really appreciate your effort, but for a further consideration, I might suggest you building your own repo and npm package.

**Comment by namikazebadri** [comment]
Yes ken.., i appreciate your suggestion. I have created a fork from your repo and new npm package too. I think i will try to improve it further for broader usability. 

Best Regards.

**Pull request closed without merging**
